version: '3.8'

services:
  web:
    image: yashi01/weather-app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
